[build]
  publish = "."

[[redirects]]
  from = "/t/:slug"
  to = "/tip.html?s=:slug"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/confirm"
  to = "/confirm.html"
  status = 200

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
